# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # All Vagrant configuration is done here. The most common configuration
    # options are documented and commented below. For a complete reference,
    # please see the online documentation at vagrantup.com.

    # Every Vagrant virtual environment requires a box to build off of.
    ## VirtualBox
    # config.vm.box = "ubuntu/xenial64"
    ## VMWare
    config.vm.box = "geerlingguy/ubuntu1604"


    # Provision
    config.vm.provision :shell, :path => "provision/provision.sh"

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    config.vm.network :forwarded_port, guest: 80, host: 8901
    config.vm.network :forwarded_port, guest: 22, host: 2204


    # Synced folder
    ## Default
    # config.vm.synced_folder "../magento2/", "/var/www/magento2", id: "ubuntu", owner: "ubuntu", group: "www-data", mount_options: ["dmode=775,fmode=664"]

    ## Sync with NFS
    # config.vm.synced_folder "../magento2/", "/var/www/magento2", nfs: true, mount_options: ["nolock", "async"], bsd__nfs_options: ["alldirs","async","nolock"]

    ## Sync with vagrant-bindfs
    # config.vm.synced_folder     "../magento2/", "/vagrant-nfs", type: "nfs"
    # config.bindfs.bind_folder   "/vagrant-nfs", "/var/www/magento2/", owner: "www-data", group: "vagrant", perms: "u=rwx:g=rwx:o=rwx"


    # VirtualBox settings
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

    # VMWare settings
    config.vm.provider "vmware_fusion" do |v|
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "2"
    end


    # Host Manager
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    config.vm.define 'magento2' do |node|
        node.vm.hostname = 'magento2'
        node.vm.network :private_network, ip: '192.168.77.4'
        node.hostmanager.aliases = %w(magento2.dev www.magento2.dev)
    end
end
